name: refill_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  image_picker: ^1.1.1
  bouncing_widget: ^2.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_naver_login: ^1.8.0
  http: ^1.2.2
  http_parser: ^4.0.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mime: ^1.0.5
  flutter_secure_storage: ^4.2.1
  path: ^1.9.0
  flutter_dotenv: ^5.1.0
  flutter_config: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - .env
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/font/Pretendard-Extra-Light.ttf
          weight: 200
        - asset: assets/font/Pretendard-Light.ttf
          weight: 300
        - asset: assets/font/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/font/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/font/Pretendard-Semi-Bold.ttf
          weight: 600
        - asset: assets/font/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/font/Pretendard-Extra-Bold.ttf
          weight: 800
        - asset: assets/font/Pretendard-Black.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"